version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gptb2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gptb2_network

  backend:
    build: ./backend
    container_name: gptb2_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
    ports:
      - "${PORT}:5000"
    depends_on:
      - mysql
    networks:
      - gptb2_network

  frontend:
    build: ./frontend
    container_name: gptb2_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - gptb2_network

volumes:
  mysql_data:

networks:
  gptb2_network:
    driver: bridge